---
language: node_js
node_js:
  - 16.8.0

branches:
  only:
    - master

cache:
  directories:
    - $(yarn cache dir)

install:
  - yarn

script:
  - yarn build

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    target-branch: master
    local-dir: build
    on:
      branch: master
